name: ci_macos
env:
  HOMEBREW_NO_INSTALL_CLEANUP: 1
  CTEST_SITE: GitHub_MacOS
  CTEST_PARALLEL_LEVEL: 3

on:
  push:
    paths:
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_macos.yml"

jobs:

  hdf5:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - run: cmake -P scripts/install_prereq.cmake
      timeout-minutes: 15

# CI is too slow for 3d_glow
    - name: Debug configure
      run: cmake --preset debug
      env:
        CC: gcc-10
        CXX: g++-10
        FC: gfortran-10

    - name: Debug build
      run: cmake --build build

    - name: Debug test
      run: ctest --preset default -E 3d

    - name: Release configure
      run: cmake --preset default
      env:
        CC: gcc-10
        CXX: g++-10
        FC: gfortran-10

    - name: Release build
      run: cmake --build build

    - name: Release test
      run: ctest --preset default -E 3d
