name: ci_windows
env:
  CMAKE_GENERATOR: Ninja
  CTEST_SITE: GitHub_Windows
  CTEST_PARALLEL_LEVEL: 2

on:
  push:
    paths:
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_windows.yml"

jobs:

  no_mpi:
    timeout-minutes: 20
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-gcc-fortran
          mingw-w64-x86_64-hdf5
          mingw-w64-x86_64-lapack

    - uses: actions/checkout@v2

    - name: Release Configure
      run: cmake --preset default

    - name: Release build
      run: cmake --build build

    - name: Release test
      run: ctest --preset default -E 3d


    - name: Debug configure
      run: cmake --preset debug

    - name: Debug build
      run: cmake --build build

    - name: Debug test
      run: ctest --preset default -E 3d
